config/routes.rb
Rails.application.routes.draw do
  get 'calculator/index'
  post 'calculator/solve'
  # get '/solve' => 'calculator#solve'
  root 'calculator#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController
  include ApplicationHelper
  def index
  end
  def solve
    string_input = params[:user_input]
    if !check_input(string_input)
      flash[:error] = "Input string is not valid, please make sure the string doesn't have letters, special characters or having extra signs"
      redirect_to calculator_index_path and return
    end


    @solution = calculate_str(string_input)
    @original_input = string_input
    respond_to do |format|
      # format.js {render js: "$('#solution').html('Solution: #{solution.to_s}')"}
      format.js {}
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  SIGN = ["+","-","*","/"]
  def check_input(str)
    # string can't include letters or special characters
    if str.match(/[a-zA-Z&^!@#$%]+/)
      return false
    end
    num_arr,sign_arr = split_numers_and_signs_to_array(str)
    first_char = str.strip.chars[0]
    if SIGN.include?(first_char)
      return false if ["*","/"].include?(first_char)
      # numers length should equal to sign length
      if num_arr.length == sign_arr.length
        return true
      else
        return false
      end
    else
      #  if the string begins with a number then there should be more numbers than signs
      if num_arr.length == sign_arr.length + 1
        return true
      else
        return false
      end
    end

  end

  def split_numers_and_signs_to_array(str)
    sign_arr = []
    num_arr = []

    parsed_arr = str.split(%r{(\+|\-|\/|\*)})
    parsed_arr.compact!
    parsed_arr.delete("")
    parsed_arr.each do |x|
      if SIGN.include?(x)
        sign_arr << x
      else
        num_arr << x.to_i
      end
    end
    return num_arr,sign_arr
  end

  def calculate_str(str)
    div_arr = []
    multiply_arr = []
    total = 0
    num_arr,sign_arr = split_numers_and_signs_to_array(str)

    # get each number start from the end
    num_arr.length.times do
      current_num = num_arr.pop
      current_sign = (sign_arr.pop || "+")

      case current_sign
        when "+", "-"
          #  take current number multiply by product of all number in multiply_arr, if empty multiply by 1
          sub_sum = current_num * (multiply_arr.inject(&:*) || 1)
          # multiply all numbers in the div_array, if empty then divide by 1, else take the sub_sum divide that number
          sub_sum = sub_sum.fdiv(div_arr.inject(&:*)|| 1)

          if current_sign == "+"
            total+= sub_sum
          else
            total-= sub_sum
          end

          # reset the array
          multiply_arr = []
          div_arr = []

        when "*"
          multiply_arr << current_num

        when "/"
          div_arr << current_num
      end
    end


    return (total%1).zero? ? total.to_i : total.round(2)

  end
end

app/helpers/calculator_helper.rb
module CalculatorHelper
end

app/views/calculator/index.html.erb
<h1>Calculator</h1>
<h3>Input example:
  5*3+1+6/2+9*100</h3>
<% flash.each do |key, value| %>
  <%= content_tag :div, value, id: "flash_error" %>
<% end %>
<%= form_with url: calculator_solve_path do%>
  <%= text_field_tag(:user_input) %>
  <%= submit_tag (:calculate) %>
<% end %>
<div id="solution"></div>

app/views/calculator/solve.js.erb
$('#flash_error').remove();
$('#solution').html('<%= @original_input %> = <%= @solution.to_s%>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calculator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>